name: The Bondi Blends
favicon: null
layout_spectrum: 0.45088028884492815
typography_spectrum: 0.3027502400800586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.699942389735952
  lightness: 0.9278053673915565
  saturation: 0.3438054344151169
  rhythmicContrast: 0.8931105092633516
purpose: []
