name: The Bondi Blends
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54167
title: The Bondi Blends
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ad66a0'
    - '#2cfcfe'
    - '#fc198f'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
